const photos = [
  "/nft-images/1.jpg",
  "/nft-images/2.jpg",
  "/nft-images/3.jpg",
  "/nft-images/4.jpg",
  "/nft-images/5.jpg",
  "/nft-images/6.jpg",
  "/nft-images/7.jpg",
  "/nft-images/8.jpg",
  "/nft-images/9.jpg",
  "/nft-images/10.jpg",
  "/nft-images/111.jpg",
  "/nft-images/12.jpg",
  "/nft-images/13.jpg",
  "/nft-images/14.jpg",
  "/nft-images/15.jpg",
  "/nft-images/16.jpg",
  "/nft-images/17.jpg",
  "/nft-images/18.jpg",
  "/nft-images/19.jpg",
  "/nft-images/20.jpg",
];
const imageData = [
  {
    image: "/nft-images/zion-trans-scaled.png",
    name: "NFT",
    description: "NFT 1 description",
    price: "1",
    dna:"1345",
    id: "1",
  },
  {
    image: "/nft-images/zion-trans-scaled.png",
    name: "NFT",
    description: "NFT 2 description",
    price: "2",
    dna:"1433",
    id: "2",
  },
  {
    image: "/nft-images/zion-trans-scaled.png",
    name: "NFT",
    description: "NFT 3 description",
    price: "3",
    dna:"1553",
    id: "3",
  },
  {
    image: "/nft-images/zion-trans-scaled.png",
    name: "NFT",
    description: "NFT 4 description",
    price: "4",
    dna:"1921",
    id: "4",
  },
  {
    image: "/nft-images/zion-trans-scaled.png",
    name: "NFT",
    description: "NFT 5 description",
    price: "5",
    dna:"2090",
    id: "5",
  },
  {
    image: "/nft-images/zion-trans-scaled.png",
    name: "NFT",
    description: "NFT 5 description",
    price: "5",
    dna:"2090",
    id: "6",
  },
  {
    image: "/nft-images/zion-trans-scaled.png",
    name: "NFT",
    description: "NFT 5 description",
    price: "5",
    dna:"2090",
    id: "7",
  },
  {
    image: "/nft-images/zion-trans-scaled.png",
    name: "NFT",
    description: "NFT 5 description",
    price: "5",
    dna:"2090",
    id: "8",
  },
  {
    image: "/nft-images/zion-trans-scaled.png",
    name: "NFT",
    description: "NFT 5 description",
    price: "5",
    dna:"2090",
    id: "9",
  },
];

const points = [
  [11, 2, 12, 2],
  [18, 6, 7, 1],
  [29, 5, 12, 3],
  [16, 10, 13, 3],
  [30, 14, 5, 2],
];
export { imageData, points };
